on:
  push:
    tags: ['v*']
jobs:
  build:
    runs-on: codeberg-small-lazy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:package

      - name: set version to tag name
        run: npm version "${FORGEJO_REF_NAME#v}" --no-git-tag-version

      - name: Publish to npm
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NAMED_EVENT_HUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NAMED_EVENT_HUB_TOKEN }}